<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class RaceSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('races')->truncate();
        Schema::enableForeignKeyConstraints();

        $races = [
            // ==================== CHIENS (IDs 1-33) ====================
            [
                'id' => 1,
                'nom' => 'CHIOT HUSKY SIBERIEN DISPONIBLE',
                'slug' => 'husky-siberien',
                'categorie' => 'chien',
                'description' => 'Le Husky Sibérien est un chien de traîneau originaire de Sibérie. C\'est un chien énergique, intelligent et sociable.',
                'taille' => '50-60 cm',
                'poids' => '16-27 kg',
                'esperance_vie' => '12-14 ans',
                'prix_moyen' => '700-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 2,
                'nom' => 'CHIOT POMSKY',
                'slug' => 'pomsky',
                'categorie' => 'chien',
                'description' => 'Le Pomsky est un croisement entre le Husky Sibérien et le Spitz nain.',
                'taille' => '25-38 cm',
                'poids' => '4-11 kg',
                'esperance_vie' => '13-15 ans',
                'prix_moyen' => '750-2000 €',
                'is_active' => true,
            ],
            [
                'id' => 3,
                'nom' => 'CHIOT GOLDEN RETRIEVER',
                'slug' => 'golden-retriever',
                'categorie' => 'chien',
                'description' => 'Le Golden Retriever est un chien de rapport originaire d\'Écosse.',
                'taille' => '51-61 cm',
                'poids' => '25-34 kg',
                'esperance_vie' => '10-12 ans',
                'prix_moyen' => '700-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 4,
                'nom' => 'CHIOT SPITZ NAIN',
                'slug' => 'spitz-nain-pomeranian',
                'categorie' => 'chien',
                'description' => 'Le Spitz Nain, aussi appelé Pomeranian, est un chien de petite taille.',
                'taille' => '18-22 cm',
                'poids' => '1.5-3.5 kg',
                'esperance_vie' => '12-16 ans',
                'prix_moyen' => '1000-2500 €',
                'is_active' => true,
            ],
            [
                'id' => 5,
                'nom' => 'CHIOT YORKSHIRE',
                'slug' => 'yorkshire-terrier',
                'categorie' => 'chien',
                'description' => 'Le Yorkshire Terrier est un chien de petite taille originaire d\'Angleterre.',
                'taille' => '15-23 cm',
                'poids' => '1.5-3.5 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '700-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 6,
                'nom' => 'CAVALIER KING CHARLES',
                'slug' => 'cavalier-king-charles',
                'categorie' => 'chien',
                'description' => 'Le Cavalier King Charles Spaniel est un chien affectueux et élégant.',
                'taille' => '30-33 cm',
                'poids' => '5-8 kg',
                'esperance_vie' => '9-14 ans',
                'prix_moyen' => '700-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 7,
                'nom' => 'CHIOT JACK RUSSEL',
                'slug' => 'jack-russell-terrier',
                'categorie' => 'chien',
                'description' => 'Le Jack Russell Terrier est un chien énergique et courageux.',
                'taille' => '25-30 cm',
                'poids' => '5-8 kg',
                'esperance_vie' => '13-16 ans',
                'prix_moyen' => '650-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 8,
                'nom' => 'Cachorro Caniche',
                'slug' => 'caniche',
                'categorie' => 'chien',
                'description' => 'Le Caniche est un chien intelligent, élégant et hypoallergénique.',
                'taille' => '24-60 cm',
                'poids' => '2-25 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '800-2000 €',
                'is_active' => true,
            ],
            [
                'id' => 9,
                'nom' => 'Cachorro Dachshund',
                'slug' => 'dachshund-teckel',
                'categorie' => 'chien',
                'description' => 'Le Teckel est un chien de petite taille aux pattes courtes.',
                'taille' => '20-27 cm',
                'poids' => '4-9 kg',
                'esperance_vie' => '12-16 ans',
                'prix_moyen' => '600-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 10,
                'nom' => 'Cachorro Boyero de Berna',
                'slug' => 'boyer-bernois',
                'categorie' => 'chien',
                'description' => 'Le Bouvier Bernois est un chien doux et affectueux.',
                'taille' => '58-70 cm',
                'poids' => '36-50 kg',
                'esperance_vie' => '6-8 ans',
                'prix_moyen' => '800-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 11,
                'nom' => 'Cachorro Yorkie',
                'slug' => 'yorkie',
                'categorie' => 'chien',
                'description' => 'Le Yorkie est un petit chien affectueux et plein d\'énergie.',
                'taille' => '15-23 cm',
                'poids' => '1.5-3.5 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '700-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 12,
                'nom' => 'Cachorro Maltese',
                'slug' => 'maltese-bichon-maltais',
                'categorie' => 'chien',
                'description' => 'Le Bichon Maltais est un petit chien au pelage blanc soyeux.',
                'taille' => '20-25 cm',
                'poids' => '2-4 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '800-2000 €',
                'is_active' => true,
            ],
            [
                'id' => 13,
                'nom' => 'Cachorro Bichon Frise',
                'slug' => 'bichon-frise',
                'categorie' => 'chien',
                'description' => 'Le Bichon Frisé est un chien joyeux et hypoallergénique.',
                'taille' => '23-30 cm',
                'poids' => '3-6 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '800-1800 €',
                'is_active' => true,
            ],
            [
                'id' => 14,
                'nom' => 'Cachorro Ibiza hound',
                'slug' => 'ibizan-hound-podenco-ibicenco',
                'categorie' => 'chien',
                'description' => 'Le Podenco Ibicenco est un chien élégant originaire des Baléares.',
                'taille' => '56-72 cm',
                'poids' => '20-25 kg',
                'esperance_vie' => '12-14 ans',
                'prix_moyen' => '600-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 15,
                'nom' => 'Cachorro De agua espanol',
                'slug' => 'chien-eau-espagnol',
                'categorie' => 'chien',
                'description' => 'Le Chien d\'Eau Espagnol est un excellent chien de travail.',
                'taille' => '40-50 cm',
                'poids' => '12-22 kg',
                'esperance_vie' => '10-14 ans',
                'prix_moyen' => '700-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 16,
                'nom' => 'Cachorro Presa canario',
                'slug' => 'presa-canario',
                'categorie' => 'chien',
                'description' => 'Le Presa Canario est un chien puissant, loyal et protecteur.',
                'taille' => '55-66 cm',
                'poids' => '40-65 kg',
                'esperance_vie' => '8-10 ans',
                'prix_moyen' => '800-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 17,
                'nom' => 'Cachorros Pastor Australiano',
                'slug' => 'berger-australien',
                'categorie' => 'chien',
                'description' => 'Le Berger Australien est un chien intelligent et énergique.',
                'taille' => '46-58 cm',
                'poids' => '18-30 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '700-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 18,
                'nom' => 'Cachorro Labrador',
                'slug' => 'labrador-retriever',
                'categorie' => 'chien',
                'description' => 'Le Labrador est le chien de famille par excellence.',
                'taille' => '54-57 cm',
                'poids' => '25-36 kg',
                'esperance_vie' => '10-12 ans',
                'prix_moyen' => '600-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 19,
                'nom' => 'Cachorro Pastor Aleman',
                'slug' => 'berger-allemand',
                'categorie' => 'chien',
                'description' => 'Le Berger Allemand est un chien intelligent et loyal.',
                'taille' => '55-65 cm',
                'poids' => '22-40 kg',
                'esperance_vie' => '9-13 ans',
                'prix_moyen' => '500-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 20,
                'nom' => 'Cachorro Chihuahua',
                'slug' => 'chihuahua',
                'categorie' => 'chien',
                'description' => 'Le Chihuahua est la plus petite race de chien.',
                'taille' => '15-23 cm',
                'poids' => '1-3 kg',
                'esperance_vie' => '12-18 ans',
                'prix_moyen' => '600-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 21,
                'nom' => 'Cachorro Pomerania',
                'slug' => 'pomeranian-spitz-nain',
                'categorie' => 'chien',
                'description' => 'Le Spitz Nain est un petit chien au pelage abondant.',
                'taille' => '18-22 cm',
                'poids' => '1.5-3.5 kg',
                'esperance_vie' => '12-16 ans',
                'prix_moyen' => '800-2500 €',
                'is_active' => true,
            ],
            [
                'id' => 22,
                'nom' => 'Cachorro Rottweiler',
                'slug' => 'rottweiler',
                'categorie' => 'chien',
                'description' => 'Le Rottweiler est un chien puissant et loyal.',
                'taille' => '56-68 cm',
                'poids' => '35-50 kg',
                'esperance_vie' => '8-10 ans',
                'prix_moyen' => '600-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 23,
                'nom' => 'Cachorro Maltipoo',
                'slug' => 'maltipoo',
                'categorie' => 'chien',
                'description' => 'Le Maltipoo est un croisement hypoallergénique.',
                'taille' => '20-35 cm',
                'poids' => '2-6 kg',
                'esperance_vie' => '10-15 ans',
                'prix_moyen' => '800-2000 €',
                'is_active' => true,
            ],
            [
                'id' => 24,
                'nom' => 'Cachorro Pug',
                'slug' => 'carlin-pug',
                'categorie' => 'chien',
                'description' => 'Le Carlin est un chien affectueux et comique.',
                'taille' => '25-35 cm',
                'poids' => '6-8 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '600-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 25,
                'nom' => 'Cachorros Goldendoodle',
                'slug' => 'goldendoodle',
                'categorie' => 'chien',
                'description' => 'Le Goldendoodle est un croisement hypoallergénique.',
                'taille' => '35-60 cm',
                'poids' => '15-30 kg',
                'esperance_vie' => '10-15 ans',
                'prix_moyen' => '1000-2500 €',
                'is_active' => true,
            ],
            [
                'id' => 26,
                'nom' => 'Cachorro Bulldog francés',
                'slug' => 'bulldog-francais',
                'categorie' => 'chien',
                'description' => 'Le Bulldog Français est un excellent chien de compagnie.',
                'taille' => '25-35 cm',
                'poids' => '8-14 kg',
                'esperance_vie' => '10-12 ans',
                'prix_moyen' => '1000-2500 €',
                'is_active' => true,
            ],
            [
                'id' => 27,
                'nom' => 'Cachorro Bulldog inglés',
                'slug' => 'bulldog-anglais',
                'categorie' => 'chien',
                'description' => 'Le Bulldog Anglais est un chien calme et affectueux.',
                'taille' => '31-40 cm',
                'poids' => '18-25 kg',
                'esperance_vie' => '8-10 ans',
                'prix_moyen' => '800-1800 €',
                'is_active' => true,
            ],
            [
                'id' => 28,
                'nom' => 'Cachorro Cane Corso',
                'slug' => 'cane-corso',
                'categorie' => 'chien',
                'description' => 'Le Cane Corso est un chien puissant et protecteur.',
                'taille' => '60-68 cm',
                'poids' => '40-50 kg',
                'esperance_vie' => '10-12 ans',
                'prix_moyen' => '800-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 29,
                'nom' => 'Cachorro Boston Terrier',
                'slug' => 'boston-terrier',
                'categorie' => 'chien',
                'description' => 'Le Boston Terrier est un petit chien élégant.',
                'taille' => '30-40 cm',
                'poids' => '5-11 kg',
                'esperance_vie' => '11-13 ans',
                'prix_moyen' => '800-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 30,
                'nom' => 'Cachorro Boxer',
                'slug' => 'boxer',
                'categorie' => 'chien',
                'description' => 'Le Boxer est un chien énergique et joueur.',
                'taille' => '53-63 cm',
                'poids' => '25-32 kg',
                'esperance_vie' => '10-12 ans',
                'prix_moyen' => '600-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 31,
                'nom' => 'Cachorro Border Collie',
                'slug' => 'border-collie',
                'categorie' => 'chien',
                'description' => 'Le Border Collie est le chien le plus intelligent.',
                'taille' => '46-56 cm',
                'poids' => '12-20 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '600-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 32,
                'nom' => 'Cachorro Galgo espanol',
                'slug' => 'galgo-espagnol',
                'categorie' => 'chien',
                'description' => 'Le Galgo Espagnol est un lévrier élégant.',
                'taille' => '62-70 cm',
                'poids' => '25-30 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '500-1000 €',
                'is_active' => true,
            ],
            [
                'id' => 33,
                'nom' => 'Cachorros Pomsky',
                'slug' => 'pomsky-2',
                'categorie' => 'chien',
                'description' => 'Le Pomsky a l\'apparence d\'un husky en petit format.',
                'taille' => '25-38 cm',
                'poids' => '4-11 kg',
                'esperance_vie' => '13-15 ans',
                'prix_moyen' => '750-2000 €',
                'is_active' => true,
            ],

            // ==================== CHATONS (IDs 34-46) ====================
            [
                'id' => 34,
                'nom' => 'CHATON BENGALE',
                'slug' => 'bengal-chat',
                'categorie' => 'chat',
                'description' => 'Le Bengal est un chat au pelage tacheté.',
                'taille' => '30-45 cm',
                'poids' => '4-8 kg',
                'esperance_vie' => '12-16 ans',
                'prix_moyen' => '650-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 35,
                'nom' => 'CHATON SAVANNAH',
                'slug' => 'savannah-chat',
                'categorie' => 'chat',
                'description' => 'Le Savannah est un chat grand et actif.',
                'taille' => '40-60 cm',
                'poids' => '5-12 kg',
                'esperance_vie' => '12-20 ans',
                'prix_moyen' => '850-2500 €',
                'is_active' => true,
            ],
            [
                'id' => 36,
                'nom' => 'CHATON SPHYNX',
                'slug' => 'sphynx-chat',
                'categorie' => 'chat',
                'description' => 'Le Sphynx est un chat sans poils, affectueux.',
                'taille' => '20-30 cm',
                'poids' => '3-5 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '850-2000 €',
                'is_active' => true,
            ],
            [
                'id' => 37,
                'nom' => 'CHATON BLEU RUSSE',
                'slug' => 'bleu-russe-chat',
                'categorie' => 'chat',
                'description' => 'Le Bleu Russe est un chat calme et intelligent.',
                'taille' => '20-25 cm',
                'poids' => '3-5 kg',
                'esperance_vie' => '15-20 ans',
                'prix_moyen' => '700-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 38,
                'nom' => 'CHATON CHARTREUX',
                'slug' => 'chartreux-chat',
                'categorie' => 'chat',
                'description' => 'Le Chartreux est un chat calme et doux.',
                'taille' => '20-30 cm',
                'poids' => '4-7 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '650-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 39,
                'nom' => 'CHATON RAGDOLL',
                'slug' => 'ragdoll-chat',
                'categorie' => 'chat',
                'description' => 'Le Ragdoll est un chat grand et calme.',
                'taille' => '25-35 cm',
                'poids' => '4-9 kg',
                'esperance_vie' => '12-17 ans',
                'prix_moyen' => '650-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 40,
                'nom' => 'CHATON SIBERIEN',
                'slug' => 'siberien-chat',
                'categorie' => 'chat',
                'description' => 'Le Sibérien est un chat hypoallergénique.',
                'taille' => '25-35 cm',
                'poids' => '4-9 kg',
                'esperance_vie' => '12-18 ans',
                'prix_moyen' => '650-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 41,
                'nom' => 'CHATON MAIN COON',
                'slug' => 'maine-coon-chat',
                'categorie' => 'chat',
                'description' => 'Le Maine Coon est un chat très grand, surnommé "gentil géant".',
                'taille' => '25-40 cm',
                'poids' => '4-10 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '650-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 42,
                'nom' => 'BRITISH SHORTHAIR',
                'slug' => 'british-shorthair',
                'categorie' => 'chat',
                'description' => 'Le British Shorthair est un chat calme et indépendant.',
                'taille' => '30-35 cm',
                'poids' => '4-8 kg',
                'esperance_vie' => '12-17 ans',
                'prix_moyen' => '650-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 43,
                'nom' => 'CHATON BRITISH LONGHAIR',
                'slug' => 'british-longhair',
                'categorie' => 'chat',
                'description' => 'Le British Longhair est la version à poil long.',
                'taille' => '30-35 cm',
                'poids' => '4-8 kg',
                'esperance_vie' => '12-17 ans',
                'prix_moyen' => '550-1200 €',
                'is_active' => true,
            ],
            [
                'id' => 44,
                'nom' => 'CHATON SCOTTISH FOLD',
                'slug' => 'scottish-fold',
                'categorie' => 'chat',
                'description' => 'Le Scottish Fold a les oreilles repliées.',
                'taille' => '25-30 cm',
                'poids' => '3-6 kg',
                'esperance_vie' => '11-14 ans',
                'prix_moyen' => '650-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 45,
                'nom' => 'CHATON SACRE DE BIRMANIE',
                'slug' => 'sacred-de-birmanie',
                'categorie' => 'chat',
                'description' => 'Le Sacré de Birmanie est un chat doux aux yeux bleus.',
                'taille' => '25-30 cm',
                'poids' => '3-6 kg',
                'esperance_vie' => '12-16 ans',
                'prix_moyen' => '650-1500 €',
                'is_active' => true,
            ],
            [
                'id' => 46,
                'nom' => 'CHATON SIAMOIS',
                'slug' => 'siamois-chat',
                'categorie' => 'chat',
                'description' => 'Le Siamois est un chat très sociable et bavard.',
                'taille' => '25-30 cm',
                'poids' => '3-5 kg',
                'esperance_vie' => '12-15 ans',
                'prix_moyen' => '650-1200 €',
                'is_active' => true,
            ],

            // ==================== OISEAUX (ID 47) ====================
            [
                'id' => 47,
                'nom' => 'Gris du Gabon (Perroquet)',
                'slug' => 'perroquet-gris-du-gabon',
                'categorie' => 'oiseau',
                'description' => 'Le Perroquet Gris du Gabon est un oiseau très intelligent.',
                'taille' => '35-42 cm',
                'poids' => '400-600 g',
                'esperance_vie' => '40-80 ans',
                'prix_moyen' => '700-2000 €',
                'is_active' => true,
            ],
        ];

        foreach ($races as $race) {
            DB::table('races')->insert($race);
        }

        $this->command->info('✅ ' . count($races) . ' races ont été insérées avec succès !');
    }
}